//! Drives the generated petstore client end to end against a local mock server: typed models,
//! query/header/path parameters, JSON bodies, bearer auth, typed API errors, undocumented-status
//! handling, the transient-failure classifier, and the bring-your-own-policy retry adapter.
//! Everything runs on 127.0.0.1 — no external API, no real credentials.

use std::future::Future;
use std::io::{BufRead, BufReader, Read, Write};
use std::net::{SocketAddr, TcpListener, TcpStream};
use std::pin::Pin;
use std::sync::atomic::{AtomicU32, Ordering};
use std::sync::Arc;
use std::time::Duration;

use secrecy::SecretString;

// The client generated by build.rs. Its file carries no inner attributes, so it can be included
// straight from OUT_DIR. A build.rs may instead target `src/petstore.rs` for committed output.
mod petstore {
    include!(concat!(env!("OUT_DIR"), "/petstore.rs"));
}

use petstore::{
    exponential_backoff, types, Client, Credential, Error, HttpBackend, ReqwestBackend,
    RetryBackend, RetryOutcome, RetryPolicy,
};

const TOKEN: &str = "let-me-in";

/// How many times the flaky route has been hit; it fails transiently (503) on the first attempt,
/// then serves 200 — so a retrying client succeeds where a plain one would surface the 503.
static FLAKY_HITS: AtomicU32 = AtomicU32::new(0);

/// A bring-your-own retry policy: retry transient outcomes with exponential backoff, up to a cap.
/// The wait is built from the caller's own async timer (`tokio::time::sleep`) — the spargen runtime
/// ships no timer and never depends on tokio; timing is supplied here.
struct ExponentialBackoff {
    max_retries: u32,
}

impl RetryPolicy for ExponentialBackoff {
    fn retry<'a>(
        &'a self,
        attempt: u32,
        outcome: &RetryOutcome<'_>,
    ) -> Option<Pin<Box<dyn Future<Output = ()> + Send + 'a>>> {
        if attempt < self.max_retries && outcome.is_transient() {
            let wait =
                exponential_backoff(attempt, Duration::from_millis(10), Duration::from_millis(200));
            Some(Box::pin(tokio::time::sleep(wait)))
        } else {
            None
        }
    }
}

#[tokio::main(flavor = "current_thread")]
async fn main() {
    let addr = spawn_mock_server();
    let base_url = format!("http://{addr}");
    println!("mock petstore listening on {base_url}");

    let client = Client::new(&base_url)
        .unwrap()
        .with_credential("bearerAuth", Credential::Bearer(SecretString::from(TOKEN)));

    // The spec's server is templated (`http://{host}:{port}`), so spargen generates a typed builder
    // whose variables default to a resolvable URL. The example dials the mock's ephemeral port
    // instead, but the typed surface is real and is exercised here.
    assert_eq!(petstore::servers::default_url(), "http://127.0.0.1:0");
    assert_eq!(
        petstore::servers::Server::new()
            .host("example.test")
            .port("8443")
            .url(),
        "http://example.test:8443"
    );

    // List with query + header parameters, built via the fluent optional-param setters. `filter` is
    // a `deepObject`, so each member travels as its own `filter[member]=value` pair.
    let pets = client
        .list_pets(Some(
            petstore::ListPetsParams::default()
                .limit(10)
                .status(types::Status::Available)
                .x_request_id("example-1".to_owned())
                .filter(types::PetFilter {
                    name: Some("Rex".to_owned()),
                    tag: None,
                    additional: Default::default(),
                }),
        ))
        .await
        .expect("list_pets");
    assert_eq!(pets.status(), 200);
    // A documented response header is read through a typed accessor — an explicit second step, so a
    // malformed header can never turn a successful call into a failure.
    let totals = petstore::ListPetsStatus200Headers::from_response(&pets).expect("typed headers");
    assert_eq!(totals.x_total_count, 1);
    let pets = pets.into_inner();
    assert_eq!(pets.len(), 1);
    println!(
        "listed {} of {} available pet(s): {}",
        pets.len(),
        totals.x_total_count,
        pets[0].name
    );

    // Create with a typed JSON body.
    let created = client
        .create_pet(&types::NewPet {
            name: "Bella".to_owned(),
            tag: Some("dog".to_owned()),
            additional: Default::default(),
        })
        .await
        .expect("create_pet");
    assert_eq!(created.status(), 201);
    let created = created.into_inner();
    println!("created pet #{} ({})", created.id, created.name);

    // Fetch by path parameter.
    let pet = client.get_pet("1".to_owned()).await.expect("get_pet");
    assert_eq!(pet.into_inner().status, types::Status::Available);
    println!("fetched pet #1");

    // A documented 404 arrives as the operation's typed error body.
    match client.get_pet("999".to_owned()).await {
        Err(Error::Api(response)) => {
            assert_eq!(response.status(), 404);
            println!("typed 404: {}", response.into_inner().message);
        }
        other => panic!("expected a typed 404, got {other:?}"),
    }

    // A multipart body with an Encoding Object: each part is sent with the Content-Type the spec
    // declares for it — `image/png` for the binary photo, `application/json` for the metadata
    // object — rather than one blanket type for the whole form.
    let stored = client
        .upload_photo(
            "1".to_owned(),
            &types::RequestBody {
                photo: bytes::Bytes::from_static(b"\x89PNG\r\n\x1a\n"),
                meta: types::PhotoMeta {
                    caption: "Rex at the park".to_owned(),
                    width: Some(1024),
                    additional: Default::default(),
                },
                additional: Default::default(),
            },
        )
        .await
        .expect("upload_photo");
    assert_eq!(stored.status(), 204);
    println!("uploaded a photo with typed multipart part Content-Types");

    // 204 maps to a unit body.
    let deleted = client.delete_pet("1".to_owned()).await.expect("delete_pet");
    assert_eq!(deleted.status(), 204);
    println!("deleted pet #1");

    // A missing credential fails before anything is sent — never a silent 401.
    let unauthenticated = Client::new(&base_url).unwrap();
    match unauthenticated.get_pet("1".to_owned()).await {
        Err(Error::RequestConstruction(error)) => {
            println!("missing credential rejected up front: {error}");
        }
        other => panic!("expected a request-construction error, got {other:?}"),
    }

    // A wrong token draws the server's (undocumented) 401: preserved raw, and not retry-worthy.
    let wrong = Client::new(&base_url)
        .unwrap()
        .with_credential("bearerAuth", Credential::Bearer(SecretString::from("nope")));
    match wrong.get_pet("1".to_owned()).await {
        Err(error @ Error::UnexpectedStatus { status, .. }) if status == 401 => {
            assert!(!error.is_transient());
            println!("undocumented 401 preserved for forensics");
        }
        other => panic!("expected an unexpected-status error, got {other:?}"),
    }

    // Bring-your-own-policy retry: wrap the default transport in a `RetryBackend` and install it via
    // `Client::with_backend`. The flaky route returns 503 once (a transient outcome) then 200; the
    // policy retries with a tokio-timed exponential backoff, so the call ultimately succeeds. The
    // client itself is unchanged — retry is a transport-seam wrapper, not a code path in `Client`.
    let retry_backend: Arc<dyn HttpBackend> = Arc::new(RetryBackend::new(
        Arc::new(ReqwestBackend::new(reqwest::Client::new())),
        Arc::new(ExponentialBackoff { max_retries: 5 }),
    ));
    let retrying = Client::with_backend(retry_backend, &base_url)
        .unwrap()
        .with_credential("bearerAuth", Credential::Bearer(SecretString::from(TOKEN)));
    let recovered = retrying
        .get_pet("flaky".to_owned())
        .await
        .expect("retry recovers from the transient 503");
    assert_eq!(recovered.status(), 200);
    assert_eq!(recovered.into_inner().name, "Comet");
    // The route was hit more than once, proving the retry actually replayed the request.
    assert!(FLAKY_HITS.load(Ordering::SeqCst) >= 2);
    println!(
        "retry recovered a flaky route after {} attempt(s)",
        FLAKY_HITS.load(Ordering::SeqCst)
    );

    println!("petstore example: all checks passed");
}

/// A deliberately tiny HTTP/1.1 mock on an ephemeral localhost port — no external service is
/// involved, so running this example repeatedly can't spam anyone.
fn spawn_mock_server() -> SocketAddr {
    let listener = TcpListener::bind("127.0.0.1:0").expect("bind mock server");
    let addr = listener.local_addr().unwrap();
    std::thread::spawn(move || {
        for stream in listener.incoming().flatten() {
            std::thread::spawn(move || handle(stream));
        }
    });
    addr
}

fn handle(mut stream: TcpStream) {
    let mut reader = BufReader::new(stream.try_clone().expect("clone stream"));
    let mut request_line = String::new();
    if reader.read_line(&mut request_line).is_err() {
        return;
    }
    let mut parts = request_line.split_whitespace();
    let (Some(method), Some(target)) = (parts.next(), parts.next()) else {
        return;
    };
    let (path, query) = match target.split_once('?') {
        Some((path, query)) => (path, query),
        None => (target, ""),
    };

    let mut authorization = String::new();
    let mut content_type = String::new();
    let mut content_length = 0usize;
    loop {
        let mut line = String::new();
        if reader.read_line(&mut line).is_err() || line.trim().is_empty() {
            break;
        }
        let Some((name, value)) = line.split_once(':') else {
            continue;
        };
        match name.to_ascii_lowercase().as_str() {
            "authorization" => authorization = value.trim().to_owned(),
            "content-type" => content_type = value.trim().to_owned(),
            "content-length" => content_length = value.trim().parse().unwrap_or(0),
            _ => {}
        }
    }
    let mut body = vec![0u8; content_length];
    if content_length > 0 && reader.read_exact(&mut body).is_err() {
        return;
    }

    // Extra response headers the route wants to add on top of the fixed ones.
    let mut extra_headers = String::new();

    let (status, response_body) = if authorization != format!("Bearer {TOKEN}") {
        ("401 Unauthorized", r#"{"message":"unauthorized"}"#.to_owned())
    } else {
        match (method, path) {
            ("GET", "/pets") => {
                // `deepObject` sends one bracketed pair per member, and an absent member sends
                // nothing at all — a JSON blob or a `filter=name,Rex` join would both be wrong.
                assert!(
                    query.contains("filter%5Bname%5D=Rex"),
                    "deepObject filter must travel as filter[name]=Rex: {query}"
                );
                assert!(
                    !query.contains("filter%5Btag%5D"),
                    "an absent deepObject member must not be sent: {query}"
                );
                extra_headers.push_str("X-Total-Count: 1\r\n");
                (
                    "200 OK",
                    r#"[{"id":"1","name":"Rex","status":"available"}]"#.to_owned(),
                )
            }
            ("POST", "/pets/1/photo") => {
                // Every part carries the Content-Type the Encoding Object declared for it.
                assert!(
                    content_type.starts_with("multipart/form-data; boundary="),
                    "photo upload must be multipart: {content_type}"
                );
                let text = String::from_utf8_lossy(&body);
                for (part, declared) in [("photo", "image/png"), ("meta", "application/json")] {
                    let at = text
                        .find(&format!("name=\"{part}\""))
                        .unwrap_or_else(|| panic!("part `{part}` missing: {text}"));
                    let header = text[at..].split("\r\n\r\n").next().unwrap_or("");
                    assert!(
                        header.contains(&format!("Content-Type: {declared}")),
                        "part `{part}` must declare {declared}: {header}"
                    );
                }
                ("204 No Content", String::new())
            }
            ("POST", "/pets") => {
                let new: serde_json::Value = serde_json::from_slice(&body).unwrap_or_default();
                let name = new["name"].as_str().unwrap_or("unnamed");
                (
                    "201 Created",
                    format!(r#"{{"id":"2","name":"{name}","status":"available"}}"#),
                )
            }
            ("GET", "/pets/1") => (
                "200 OK",
                r#"{"id":"1","name":"Rex","status":"available"}"#.to_owned(),
            ),
            // A transiently-failing route: 503 on the first hit, 200 afterward. Exercises the
            // retry adapter — a plain client sees the 503, a retrying one recovers.
            ("GET", "/pets/flaky") => {
                if FLAKY_HITS.fetch_add(1, Ordering::SeqCst) == 0 {
                    (
                        "503 Service Unavailable",
                        r#"{"message":"try again"}"#.to_owned(),
                    )
                } else {
                    (
                        "200 OK",
                        r#"{"id":"flaky","name":"Comet","status":"available"}"#.to_owned(),
                    )
                }
            }
            ("GET", _) => ("404 Not Found", r#"{"message":"no such pet"}"#.to_owned()),
            ("DELETE", "/pets/1") => ("204 No Content", String::new()),
            _ => (
                "500 Internal Server Error",
                r#"{"message":"unhandled route"}"#.to_owned(),
            ),
        }
    };

    let _ = write!(
        stream,
        "HTTP/1.1 {status}\r\nContent-Type: application/json\r\n{extra_headers}Content-Length: {}\r\nConnection: close\r\n\r\n{response_body}",
        response_body.len(),
    );
}
